# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0008_auto_20160806_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ident',
            field=models.IntegerField(default=1),
        ),
    ]
