# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Contact info', max_length=200)),
                ('contactinfo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('image', models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField(default=1)),
                ('title', models.CharField(default=b'About us 1', max_length=200)),
                ('info', models.CharField(max_length=1000)),
                ('image', models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField(default=1)),
                ('title', models.CharField(default=b'About us 1', max_length=200)),
                ('description', models.CharField(default=b'description', max_length=1000)),
                ('image', models.ImageField(null=True, upload_to=b'images/')),
                ('gallery1', models.ImageField(null=True, upload_to=b'gallery/')),
                ('gallery2', models.ImageField(null=True, upload_to=b'gallery/')),
                ('gallery3', models.ImageField(null=True, upload_to=b'gallery/')),
                ('gallery4', models.ImageField(null=True, upload_to=b'gallery/')),
                ('gallery5', models.ImageField(null=True, upload_to=b'gallery/')),
                ('gallery6', models.ImageField(null=True, upload_to=b'gallery/')),
            ],
        ),
    ]
