# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Contact info', max_length=200)),
                ('contactinfo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('image', models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField(default=1)),
                ('title', models.CharField(default=b'About us 1', max_length=200)),
                ('info', models.CharField(max_length=1000)),
                ('image', models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='store',
        ),
        migrations.RemoveField(
            model_name='room',
            name='chain',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='projectName',
        ),
        migrations.RemoveField(
            model_name='project',
            name='founded_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.AddField(
            model_name='project',
            name='ident',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=b'PROJECT TITLE', max_length=200),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
