# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161016_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('image', models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectName',
        ),
        migrations.AddField(
            model_name='miniimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Project'),
        ),
    ]
