# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161023_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='miniimage',
            name='number',
        ),
        migrations.AddField(
            model_name='miniimage',
            name='photo',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
    ]
