# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161026_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(default=b'moj projekt', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=b'none', upload_to=b'images/'),
        ),
    ]
