# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161026_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/'),
        ),
    ]
