# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161026_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniimage',
            name='photo',
        ),
        migrations.AddField(
            model_name='miniimage',
            name='image',
            field=models.ImageField(default=b'/home/ola/Documents/schemat/drf_copy/drf_sample/client/static/app/images/2_mini.jpg', upload_to=b'images/'),
        ),
        migrations.AddField(
            model_name='miniimage',
            name='number',
            field=models.CharField(default=b'1_', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
