# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20161027_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default=b'About us 1', max_length=200),
        ),
    ]
