# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20161027_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniimage',
            name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='projectphoto',
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=b'description', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery1',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery2',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery3',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery4',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery5',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery6',
            field=models.ImageField(null=True, upload_to=b'gallery/'),
        ),
        migrations.DeleteModel(
            name='MiniImage',
        ),
    ]
