# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20161027_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectphoto',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=b'images/'),
        ),
    ]
