# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20160712_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='founded_date',
            new_name='identificator',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='projectName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='website',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slogan',
        ),
        migrations.AddField(
            model_name='project',
            name='projectTitle',
            field=models.CharField(default=b'PROJECT TITLE', max_length=200),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
