# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_auto_20160806_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='identificator',
            new_name='ident',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectTitle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default=b'PROJECT TITLE', max_length=100),
        ),
    ]
