# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0014_auto_20160914_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='info',
            new_name='contactinfo',
        ),
    ]
